{
  imports = [
    ./languages
    ./autopairs.nix
    ./blink.nix
    ./comment.nix
    ./conform.nix
    ./git-worktree.nix
    ./gitsigns.nix
    ./lint.nix
    ./lsp.nix
    ./lualine.nix
    ./luasnip.nix
    ./mini.nix
    ./oil.nix
    ./snacks
    ./tmux-navigator.nix
    ./treesitter.nix
    ./web-devicons.nix
  ];
}
