name: Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Validate Nix Flake Health
        uses: DeterminateSystems/flake-checker-action@main
      - name: Nix Flake Check
        run: nix flake check
